version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /servermain.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    volumes:
      - ./server/serverconfig.ini:/serverconfig.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: python3 /localmain.py
    environment:
      - CLI_ID=1
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client_bets/config.ini:/config.ini


networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24


